# Generated by Django 4.1.7 on 2023-03-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('idPrograma', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(max_length=50)),
                ('codigo_programa', models.CharField(max_length=15)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
