# Generated by Django 4.1.7 on 2023-03-29 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programa',
            options={},
        ),
    ]
