# Generated by Django 4.1.7 on 2023-04-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0002_alter_programa_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('idAdministrativo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('cargo', models.CharField(max_length=80)),
                ('documento', models.CharField(max_length=20)),
                ('codigo', models.IntegerField()),
            ],
            options={
                'db_table': 'administrativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsistenciaEvento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horas_registradas', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'asistenciaevento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('idEstudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=80)),
                ('codigo', models.IntegerField()),
            ],
            options={
                'db_table': 'estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('No Aprobado', 'Denegado'), ('En proceso', 'Progreso')], default='En proceso', max_length=15)),
                ('correccion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('idPerfil', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=80)),
                ('correo', models.CharField(max_length=80)),
                ('contraseña', models.CharField(max_length=45)),
                ('documento', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramaEvento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'programaevento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='programa',
            options={'managed': False},
        ),
    ]
