# Generated by Django 4.1.7 on 2023-04-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('idActividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=150)),
                ('lugar', models.CharField(max_length=50)),
                ('estado', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'programaevento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActividadDia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicio', models.CharField(max_length=45)),
                ('hora_fin', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'actividaddia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('idDia', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'dia',
                'managed': False,
            },
        ),
    ]
